import Head from 'next/head';
import styled from 'styled-components';

const Container = styled.div`
  height: 100px;
  width: 100px;
  background: black;
  color: white;
`;


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        Hello World
      </Container>
    </>
  )
}
